config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "welcome#index"

  resources :nannies
  resources :on_side_nannies, :only => [:new]
  resources :in_home_nannies, :only => [:new]
  resources :users

  namespace :admin do
  	resources :users, :only => [:edit]
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BanannyV2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

       <% if current_user %>
          <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
            <% if current_user.admin? %>
              <%= link_to "登入後台", edit_admin_user_path(current_user) %>
            <% end %>
        <% else %>
          <%= link_to "登入 Facebook", user_facebook_omniauth_authorize_path %>
          <%#= link_to('登入', new_session_path(:user)) %>
        <% end %>


        <% if current_user && current_user.user_type == nil %>
          <%= image_tag current_user.fb_pic if current_user.fb_pic.present? %>
          <%= current_user.name%>

          <%= link_to('我是保母', new_nanny_path()) %>
        <% end %>

     	<p class="notice"><%= notice %></p>
    	<p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>

  <script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1692746124320256',
      xfbml      : true,
      version    : 'v2.7'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
  </script>
  <div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
  </div>
</html>